### ISSUE TITLE
Clean up model code

### ISSUE THREAD

**Issue by paul-tqh-nguyen** [paul-tqh-nguyen/joel_spolsky_text_generator#5]
Given that we have now made the page live, let's clean up the source code since the page is out there for the world to see.

**Comment by paul-tqh-nguyen** [comment]
These commits sufficiently clean up the code on a shallow level. We'll leave the in-depth cleaning for later. We've got some functionality changes to address in the meantime.

**Comment by bungfut** [comment]
#5
